// getparams.cjs
// Run with: node getparams.cjs
// Fetches parameters from Firestore and writes to src/config/params.js

const fs = require('fs');
const path = require('path');
const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');

// Path to your Firebase service account key
const serviceAccount = require(path.resolve(__dirname, 'backend/foreclosure-15f09-firebase-adminsdk-fbsvc-0fd54751e3.json'));

initializeApp({
  credential: cert(serviceAccount),
  projectId: 'foreclosure-15f09',
});

const db = getFirestore();

async function main() {
  const paramsSnap = await db.collection('parameters').get();
  const paramsObj = {};
  paramsSnap.forEach(doc => {
    const data = doc.data();
    if (data.param && data.paramValue !== undefined) {
      paramsObj[data.param] = data.paramValue;
    }
  });

  const jsContent = `// This file is auto-generated by getparams.js\n// Do not edit manually.\n\nexport default ${JSON.stringify(paramsObj, null, 2)};\n`;
  const outPath = path.resolve(__dirname, 'src/config/params.js');
  fs.writeFileSync(outPath, jsContent, 'utf8');
  console.log('Wrote params to', outPath);
}

main().catch(err => {
  console.error('Error fetching parameters:', err);
  process.exit(1);
});
