// This file is auto-generated by the getparams script.
// Do not edit manually.

export default {
  "owner_assoc_words": "HOA,Homeowners Association,Home Owners Association,Condominium Association,Condo Association,Property Owners Association,POA,Community Association,Townhome Association,Master Association,Association of Owners,Owners Association,Unit Owners Association,Neighborhood Association,Village Association,Subdivision Association,Residential Association,Management Association,Home Association,Association, Inc.,Association Inc"
};
